/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IX2Swap__factory } from "./IX2Swap__factory";
export { ScopedVault__factory } from "./ScopedVault__factory";
