/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IX2Swap,
  IX2SwapInterface,
} from "../../../src/ScopedVault.sol/IX2Swap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxDeviationBps",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "exchangeAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "path",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "closePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assetAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxDeviationBps",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "exchangeAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "path",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "openPosition",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IX2Swap__factory {
  static readonly abi = _abi;
  static createInterface(): IX2SwapInterface {
    return new Interface(_abi) as IX2SwapInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IX2Swap {
    return new Contract(address, _abi, runner) as unknown as IX2Swap;
  }
}
