/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ScopedVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agent"
      | "availableForTrading"
      | "currentExposure"
      | "deposit"
      | "executeClosePosition"
      | "executeOpenPosition"
      | "maxPerTrade"
      | "maxTotalExposure"
      | "owner"
      | "positionAmount"
      | "positionX2Swap"
      | "renounceOwnership"
      | "rescueToken"
      | "setAgent"
      | "setMaxPerTrade"
      | "setMaxTotalExposure"
      | "setTimeWindow"
      | "timeWindow"
      | "tradesInWindow"
      | "transferOwnership"
      | "usdc"
      | "vaultBalance"
      | "windowStart"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentUpdated"
      | "Deposited"
      | "LimitsUpdated"
      | "OwnershipTransferred"
      | "PositionClosed"
      | "PositionOpened"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "availableForTrading",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentExposure",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeClosePosition",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeOpenPosition",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPerTrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalExposure",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "positionAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "positionX2Swap",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPerTrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTotalExposure",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimeWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradesInWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vaultBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "windowStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableForTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeClosePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOpenPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPerTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "positionAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionX2Swap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPerTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTotalExposure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimeWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeWindow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tradesInWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "windowStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [oldAgent: AddressLike, newAgent: AddressLike];
  export type OutputTuple = [oldAgent: string, newAgent: string];
  export interface OutputObject {
    oldAgent: string;
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LimitsUpdatedEvent {
  export type InputTuple = [
    maxPerTrade: BigNumberish,
    maxTotalExposure: BigNumberish,
    timeWindow: BigNumberish
  ];
  export type OutputTuple = [
    maxPerTrade: bigint,
    maxTotalExposure: bigint,
    timeWindow: bigint
  ];
  export interface OutputObject {
    maxPerTrade: bigint;
    maxTotalExposure: bigint;
    timeWindow: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionClosedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    x2swap: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    x2swap: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    x2swap: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionOpenedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    x2swap: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    x2swap: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    x2swap: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScopedVault extends BaseContract {
  connect(runner?: ContractRunner | null): ScopedVault;
  waitForDeployment(): Promise<this>;

  interface: ScopedVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agent: TypedContractMethod<[], [string], "view">;

  availableForTrading: TypedContractMethod<[], [bigint], "view">;

  currentExposure: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  executeClosePosition: TypedContractMethod<
    [
      x2swap: AddressLike,
      positionId: BigNumberish,
      maxDeviationBps: BigNumberish,
      exchangeAddress: AddressLike,
      path: BytesLike,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  executeOpenPosition: TypedContractMethod<
    [
      x2swap: AddressLike,
      assetAmount: BigNumberish,
      maxDeviationBps: BigNumberish,
      exchangeAddress: AddressLike,
      path: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  maxPerTrade: TypedContractMethod<[], [bigint], "view">;

  maxTotalExposure: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  positionAmount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  positionX2Swap: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAgent: TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;

  setMaxPerTrade: TypedContractMethod<
    [_maxPerTrade: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxTotalExposure: TypedContractMethod<
    [_maxTotalExposure: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimeWindow: TypedContractMethod<
    [_timeWindow: BigNumberish],
    [void],
    "nonpayable"
  >;

  timeWindow: TypedContractMethod<[], [bigint], "view">;

  tradesInWindow: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  vaultBalance: TypedContractMethod<[], [bigint], "view">;

  windowStart: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "availableForTrading"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentExposure"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeClosePosition"
  ): TypedContractMethod<
    [
      x2swap: AddressLike,
      positionId: BigNumberish,
      maxDeviationBps: BigNumberish,
      exchangeAddress: AddressLike,
      path: BytesLike,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeOpenPosition"
  ): TypedContractMethod<
    [
      x2swap: AddressLike,
      assetAmount: BigNumberish,
      maxDeviationBps: BigNumberish,
      exchangeAddress: AddressLike,
      path: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "maxPerTrade"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTotalExposure"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "positionAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "positionX2Swap"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxPerTrade"
  ): TypedContractMethod<[_maxPerTrade: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxTotalExposure"
  ): TypedContractMethod<
    [_maxTotalExposure: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTimeWindow"
  ): TypedContractMethod<[_timeWindow: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tradesInWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "windowStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "LimitsUpdated"
  ): TypedContractEvent<
    LimitsUpdatedEvent.InputTuple,
    LimitsUpdatedEvent.OutputTuple,
    LimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionClosed"
  ): TypedContractEvent<
    PositionClosedEvent.InputTuple,
    PositionClosedEvent.OutputTuple,
    PositionClosedEvent.OutputObject
  >;
  getEvent(
    key: "PositionOpened"
  ): TypedContractEvent<
    PositionOpenedEvent.InputTuple,
    PositionOpenedEvent.OutputTuple,
    PositionOpenedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AgentUpdated(address,address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "LimitsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;
    LimitsUpdated: TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionClosed(uint256,address,uint256)": TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;
    PositionClosed: TypedContractEvent<
      PositionClosedEvent.InputTuple,
      PositionClosedEvent.OutputTuple,
      PositionClosedEvent.OutputObject
    >;

    "PositionOpened(uint256,address,uint256,uint256)": TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;
    PositionOpened: TypedContractEvent<
      PositionOpenedEvent.InputTuple,
      PositionOpenedEvent.OutputTuple,
      PositionOpenedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
