/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scopedVaultSol from "./ScopedVault.sol";
export type { scopedVaultSol };
export type { MockUSDC } from "./MockUSDC";
export type { MockX2Swap } from "./MockX2Swap";
